# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcloud-slim', '--tag=gcr.io/i-academy-243007/gcloud-slim', '-f', 'Dockerfile.slim', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcr.io/i-academy-243007/gcloud', '-f', 'Dockerfile', '.']

# # Simple sanity check: invoke the new gcloud container to confirm that it was
# # built correctly.
# - name: 'gcr.io/i-academy-243007/gcloud'
#   args: ['info']
# - name: 'gcr.io/i-academy-243007/gcloud-slim'
#   args: ['info']

# # Invoke a command that requires auth, to check that it gets piped through
# # correctly.
# - name: 'gcr.io/i-academy-243007/gcloud'
#   args: ['source', 'repos', 'clone', 'default']

# images:
# - 'gcr.io/i-academy-243007/gcloud'
# - 'gcr.io/i-academy-243007/gcloud-slim'

# timeout: 1200s

steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"